name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    # Ejecutar ESLint
    - name: Run ESLint
      run: npm run lint

    # Ejecutar Prettier
    - name: Run Prettier
      run: npm run format

    # Commit de los cambios (si ESLint o Prettier modificaron algo)
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'chore: lint and format code'
        branch: ${{ github.head_ref }}

    # Instalar y ejecutar Nuclei Vulnerability Scan
    - name: Nuclei Vulnerability Scan
      uses: projectdiscovery/nuclei-action@v1
      with:
        # Puedes especificar una URL para escanear
        target: "index.js"
