name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

      # Instalar Syft
    - name: Install Syft
      run: |
        wget https://github.com/anchore/syft/releases/download/v0.80.1/syft-linux-amd64-v0.80.1.tar.gz
        tar -xvf syft-linux-amd64-v0.80.1.tar.gz
        sudo mv syft /usr/local/bin/

    # Generación del SBOM
    - name: Generate SBOM
      run: |
        syft . -o json > sbom.json

    # Commit y push del archivo SBOM generado
    - name: Commit SBOM file
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'chore: add SBOM file'
        branch: ${{ github.head_ref }}
        files: 'sbom.json'

    # Ejecutar ESLint
    - name: Run ESLint
      run: npm run lint

    # Ejecutar Prettier
    - name: Run Prettier
      run: npm run format

    # Commit de los cambios (si ESLint o Prettier modificaron algo)
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'chore: lint and format code'
        branch: ${{ github.head_ref }}
